albums-url: "http://photo-app-album/users/%s/albums"
login-url: "/users/login"
token:
  expiration: 86400000 #1 day
  secret: "{cipher}AQCDZftBl4KCmiaHSZVOnPSg0UcHjH9OSTbKvExD10wUh8CQSis4q9i4KJjnS7ZTcbEDTjRqu7bOnb6X1mkrqnHOo6UyiVkoNFZm/MMnc4iNMHZJ2yNjP5+mUQUVG4xYEHzYmQpuuMoAoEDJntc9CmSIRjU1cG4RRnhkBv8CLSaye08Qs8Kb8SBpRymyz6CXG1Wf9TMLVh+VHZRC3XNS2dF/mcwekGV/cwbaxIusWZUFoX6FtvKunObWjsc4SEGHicGmfqpIxqKsv+6Z3obhk96OodRa8pBEpy8U3kWYNcctKabgwCkyp4Ce2E+mTpdj7V75Xtmt6xxqFwA7DWHwFg4pWCAxBtzWBNgMFi2nGn9wa3qoBJs5gQliM0AQ5rotCvq2j/nuoBIMNKmMV85PqD44"

spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1