albums-url: "http://photo-app-album/users/%s/albums"
login-url: "/users/login"

token:
  expiration: 864000 #10 days
  secret: hrewarhewatjawete5345jdashrak3

spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1