
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_app?serverTimezone=UTC
    username: robik
    password: "{cipher}AQAlHZ8+AjJ7nbMjcr9zra7sIJYWaOkVZVmM35yV5oTG/3qnKXJmSryasfjcp3YQMzvdIquBpvFBcvps2x9shgJUGWQ7KIx/0W1ValKQMUnXaia/N/a+IuqcL+OtNEAiT9CHaF/E6we7MzruI5Z2KshIN662jZC1f1Lhf/omcgm8FY00glT4MW80FaMoy813O1N4Q/RwNR5UfFat+3b6kXMBoIM082ndTwQ5HAv0cph+vk3lOOx4Fgf8Lou5Qpx2fdUpkB1dNfaUgTPF+/dEPckhVdDD4hE0In7BDz0ZN5VCEHuJBDEd87UHaleZxQ/O0NzBq0+Udkmxw5EpzaGuYJB8q2lzYCP9LmyPgIaASixReGSlUdEyt58nOAdezJge4x0="