
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: robik
    password: "{cipher}AQAErfLwCmbnkIrPamx251cWUuPmkwreLVGKfWjuLLeGPnDhIidEm1hhjDigTNz9KZd81vSItpkplejwJDyDKWtSjRJI9f1w9SW/4itBehh1k79ibZ4u++G/WD8zKLe4Re2W0B9MjMUlpJhPrCM5v6a7GVD3JTPUqCm1LFI9DJ8rWeB2qFPg84RrvIGhPznOotdOtBagq5DpgM/cFpdd0TMvi/ddiCcBWtUXa1kpH7+DvBu8d/GJeySu7RsHHChDT0Mik0SUoDDZWQNu9ZAt/Fu9YvXnfEm7qL5MLpeOMqL60hiPS4dAq2trol1G1RynrXFIiLPzQXXzIRKs9JY0QgAIxUfrBxGmDQ/lBP4Wwg3wAmP3M2601SeeHJww5JImC4A="